#pragma config(Motor,  port2,           leftdrivetrain, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           rightdrivetrain, tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{



}
